// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLPJxPmFF7x0Qi4YlLT4PzoUm0vKw_a7w',
    appId: '1:948323496560:web:c38e2c2498a6835ae3bab5',
    messagingSenderId: '948323496560',
    projectId: 'vytal-f1651',
    authDomain: 'vytal-f1651.firebaseapp.com',
    storageBucket: 'vytal-f1651.firebasestorage.app',
    measurementId: 'G-89STT4TFWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBepATPRBeSTn0pb-cyxB-IJo6TCQJNak',
    appId: '1:948323496560:android:c4b6d54d89bbe011e3bab5',
    messagingSenderId: '948323496560',
    projectId: 'vytal-f1651',
    storageBucket: 'vytal-f1651.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKzSE6-T1yw6SNA6busnSgvrFN_zSzM8I',
    appId: '1:948323496560:ios:ae5274a8f8a43699e3bab5',
    messagingSenderId: '948323496560',
    projectId: 'vytal-f1651',
    storageBucket: 'vytal-f1651.firebasestorage.app',
    iosBundleId: 'com.example.vytalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKzSE6-T1yw6SNA6busnSgvrFN_zSzM8I',
    appId: '1:948323496560:ios:ae5274a8f8a43699e3bab5',
    messagingSenderId: '948323496560',
    projectId: 'vytal-f1651',
    storageBucket: 'vytal-f1651.firebasestorage.app',
    iosBundleId: 'com.example.vytalApp',
  );
}
